# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Heat Pumps in Alaska
tagline:          'Get pumped!'
description:      'A 2023 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2023-Heating-Loads"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG2023-Heating-Loads/
